spring:
  shardingsphere:
    datasource:
      # 写数据源master
      master:
        url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      # 读数据源slave0
      slave0:
        url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      # 读数据源slave1
      slave1:
        url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456